apiVersion: v1
kind: Pod
metadata:
  name: nginx-fazztrack
  labels:
    env: dev
spec:
  containers:
    - name: nginx-fazztrack
      image: nginx:latest
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-fazztrack-service
spec:
  type: NodePort
  selector:
    app: nginx-fazztrack
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30025