version: '3.1'

services:
  # DATABASE
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db_mysql
      MYSQL_USER: user_fazztrack
      MYSQL_PASSWORD: pass_fazztrack
      MYSQL_ROOT_PASSWORD: root_fazztrack
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - 'mysql_network'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - 'mysql_network'

networks:
  mysql_network:

